export interface MaterialSection {
  id: string
  title: string
  shortLabel: string
  paragraphs: string[]
  sceneImage: string
  scenePosition?: string
  imageAlt: string
}

export const materialDescription =
  'Pencil, ink, and paper are not neutral supports in my work—they shape the line, the tempo, and the surface I draw on. What follows is how I choose and handle each material in the studio.'

export const materialSections: MaterialSection[] = [
  {
    id: 'pencil',
    title: 'Pencil and Graphite',
    shortLabel: 'Pencil',
    paragraphs: [
      'The pencil is a wonderful implement and my most important tool. Be it a simple lead pencil, a propelling pencil or a clutch pencil, I find it the best means to draw lines, regardless of whether they are slow and precise or quick and expressive. I can pause and then, if need be, continue the line later, smoothly and seamlessly, without any evident sign of a join.',
      'Of the three pencils I select the simple one most often, as I can use it for everything: with a pencil that is very hard — a 6H, for example — and sharpened to a fine point, I can produce fine, extremely delicate lines; with a very soft pencil, like an 8B, I can create strong black lines. One minor disadvantage of the pencil is that I have to keep sharpening it. And so as not to be constantly interrupted while drawing, I have a dozen pencils of the required grade ready-sharpened that I then use in sequence until they have lost their point. When the last pencil eventually goes blunt, I gather them all together, put them through the sharpener and start the process over again. A decent sharpening machine that can take pencils of different thicknesses and be adjusted to produce points ranging from blunt to sharp is a fixture on the drawing table.',
      'I use the propelling pencil if I want to draw lines of the same thickness. Compared to the lead pencil, there is less leeway for varying the degree of hardness and width of the line — I have never managed to produce a really black or really delicate light line with it, although it has no rival in terms of its reliability. Even after the lead has changed automatically. the thickness and hardness remain exactly the same.',
      'The ultimate tool for hatching is the clutch pencil. It has thicker leads than the propelling pencil and can be used to apply large, even areas of grey to the paper. It has sizeable leads with diameters ranging from 2 to 3.15 mm, while the fine leads of the propelling pencil are between 0.35 to 1.4 mm in diameter. You can produce smooth lines by regularly turning the pencil after each stroke to round the thick lead. By drawing these lines close together, you can create a homogeneous area with a very precise tonal value. In order to increase the homogeneity, between the lines of the cross-hatching, in which all the strokes run in the same direction with a single degree of hardness, I typically do a second application with a pencil that has a difference of at least two or three grades. Using this method, the graphite lines can be run together and blurred — almost like an aquarelle effect.',
      'By layering the lines — in other words, by superimposing many separate areas of hatching — it is possible to produce a special silky lustre generated by the wax in the lead. The wax is used for impregnation, with clay added as a binding agent and graphite as a colour pigment. The more graphite, the greater the lustre. However, repeated drawing of a line runs the risk of damaging the surface of the paper with the lead, or even tearing it. This means that the only way to achieve an even glossy tonal value is by applying careful pressure that is as constant as possible.',
    ],
    sceneImage: '/material/pencil-graphite.jpg',
    scenePosition: 'center 42%',
    imageAlt: 'Pencils and graphite drawing tools',
  },
  {
    id: 'ink',
    title: 'Ink and Pen',
    shortLabel: 'Ink',
    paragraphs: [
      'For the series »Drawings for Children and Adults«, which I have been working on intermittently since 2011, I am using black document ink, also called archive ink. The special feature of this ink is that it tends not to fade when exposed to light — even after many years it loses none or almost none of its intensity. It cannot be corrected or erased. Even when it comes into contact with water, the ink only runs somewhat, and the lines still remain visible. I use document ink in my old fountain pen, a sturdy implement with a heavy hexagonal shaft, equipped with an extra-fine (EF) nib with a pointed tip. Before using it, I rounded the end on a piece of metal emery paper so that ideally I can draw a line in any direction that has a constant breadth.',
      'For me, when I am drawing with fountain pen and ink, the key difference to the pencil is the time factor. When I’m drawing with a pencil it makes no difference how long I apply the tip to the paper, but with ink this plays a major role. If I want to produce a line of constant thickness from beginning to end, it is essential to draw with an even tempo — provided, of course, that there is a proper flow of ink from the barrel through to the nib. Because my pen is extremely heavy, I only need to place it on the paper, just touch the paper with the nib — in other words, I don’t exert any pressure of my own and simply glide across the paper to draw a line.',
      'The ambient humidity in the studio has an important influence. In summer and winter the humidity is low to normal (40 to 55 per cent); unfortunately, in spring and autumn it is always higher. In unpleasant periods with 60 to 70 per cent I try to counteract the humidity with a dehumidifier, but this still changes the lines I draw at such times: they are not as razor-sharp, and under a magnifying glass they look a little dissipated. Even the gentle scratching of the nib on the paper that I am otherwise so fond of is barely audible. I miss this acoustic support at such moments.',
    ],
    sceneImage: '/material/ink.jpg',
    scenePosition: 'center 38%',
    imageAlt: 'Fountain pen and ink drawing',
  },
  {
    id: 'paper',
    title: 'Paper',
    shortLabel: 'Paper',
    paragraphs: [
      'I mostly use fine, natural white, acid-free drawing paper with high opacity and excellent non-fade and anti-ageing properties. I prefer heavy coated fine-art paper for drawing — it has been double-sized, which gives it a robust surface smoothness that also makes it possible to overlay a number of lines one on top of the other. This kind of paper has no grain and a sealed surface with minimal roughness. This means that I can predict the results I will achieve drawing very fine and precise lines. The paper can completely absorb graphite and ink and render rich contrasts.',
      'I use paper not only as a medium for drawing on but also as a material for my paper objects. To make them, I first determine the form and then construct a cutting pattern for the individual objects, ideally consisting of a single piece of paper. I gently score the contours of the objects with a scalpel to ensure clear edges and create little equilateral triangles at the glued joints that later serve as adhesive flaps. To prevent bumps appearing in the surfaces, I carefully fold the creases along their entire length using the hard edge of my straight tweezers. Cyanoacrylate has proved successful as a glue. It sticks the paper permanently within a few seconds so that there is no way the joints can then accidentally slip out of place. Applying one drop per flap reduces the risk of glue oozing out. This adhesive allows me to work quickly and without any mess. Once the entire object, consisting of numerous individual paper shapes, is ready, I coat the paper with hot beeswax until it is fully impregnated. At the end, I completely remove any surplus wax. The effect of this procedure, a stressful process for the paper and glue flaps, is to produce a silk-matt, translucent paper surface that causes the individual objects to gleam diaphanously when light falls on them so that they shimmer like marble.',
    ],
    sceneImage: '/material/paper.jpg',
    scenePosition: 'center 50%',
    imageAlt: 'Drawing paper and paper objects',
  },
]
